### ISSUE TITLE
seperate the large llvm bins out

### ISSUE THREAD

**Issue by CR3Swapper** [backengineering/bin2bin-tests#18]
so the large llvm binaries that are in 32bit/64bit bog down CI. This repo needs to run everytime we make a push so we can see the effects we make on code coverage and stability. I suggest a change to the file structure:

```
64bit/ci/*.exe
64bit/ci/*.pdb
32bit/ci/*.exe
32bit/ci/*.pdb
```

we move the larger bins to just 32bit/*.exe and 32bit/*.pdb this way we can run them locally still without clogging up CI with huge binaries to rewrite.

**Comment by 54** [comment]
ok, disabling CI until this is done.
also need to output coverage to discord i guess
