### ISSUE TITLE
other pieces of software to test

### ISSUE THREAD

**Issue by CR3Swapper** [backengineering/bin2bin-tests#5]
- zasm tests https://github.com/zyantific/zasm/tree/master/src/tests
- z3 tests https://github.com/Z3Prover/z3/tree/master/src/test
- luajit 
- unicorn engine
- chocolatey

**Comment by CR3Swapper** [comment]
hash cat tests? https://github.com/hashcat/hashcat/blob/master/deps/xxHash/tests

**Comment by CR3Swapper** [comment]
zasm tests have all tests together in a single binary and make it difficult to compare stdout. However zasm has some nice examples which we can use to test.

zasm also has a nice benchmark exe we can use.

**Comment by CR3Swapper** [comment]
zasm example bins have been added.

https://github.com/backengineering/bintests/commit/0bdae0f0b11e2a4627cf8ed30fd73f013f6f2c4e

**Comment by CR3Swapper** [comment]
windows has SEH test binaries.

https://github.com/microsoft/compiler-tests/tree/master/seh

**Comment by CR3Swapper** [comment]
- glm (opengls math library)

https://github.com/g-truc/glm/tree/master/test

**Comment by CR3Swapper** [comment]
> windows has SEH test binaries.
> 
> https://github.com/microsoft/compiler-tests/tree/master/seh

added all of these

**Comment by 54** [comment]
https://github.com/Vector35/function_detection_test_suite/
in particular the byteweight tests for pex86/x86-64 + more im sure

**Comment by CR3Swapper** [comment]
> https://github.com/Vector35/function_detection_test_suite/ in particular the byteweight tests for pex86/x86-64 + more im sure

I dont think these are actual PE files, i downloaded and unzipped them and its not a PE?

https://github.com/Vector35/function_detection_test_suite/tree/master/byteweight/pe-x86-64

**Comment by CR3Swapper** [comment]
done
